name: ZIP Release

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Create ZIP
        run: zip -r "${{ github.event.repository.name }}.zip" . -x ".git/*"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest
          make_latest: true
          files: ${{ github.event.repository.name }}.zip